name: 'Azion AI Code Review'
description: 'Performs an AI-powered code review on pull requests'

# Define os inputs que a action pode receber
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  azion-token:
    description: 'Azion AI token'
    required: true
  prompt:
    description: 'Custom prompt for the AI code review'
    required: false
    default: |
      Analyze the following pull request and provide a summary of what it implements, including good practices, possible problems, and suggestions for improvement.
      Provide your analysis in Markdown format, starting with a general summary of the pull request.
  max-files:
    description: 'Maximum number of files to review'
    required: false
    default: '10'

# Define como a action será executada
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      shell: bash
      run: |
        npm install
        npm install @actions/github

    - name: Execute AI Code Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        AZION_TOKEN: ${{ inputs.azion-token }}
        CUSTOM_PROMPT: ${{ inputs.prompt }}
        MAX_FILES: ${{ inputs.max-files }}
      run: node ${{ github.action_path }}/code-review.mjs